_target_: guided_diffusion.script_util.create_model
image_size: 64
num_channels: 192
num_res_blocks: 3
num_heads: 4
num_heads_upsample: -1
num_head_channels: 64
attention_resolutions: "32,16,8"
channel_mult: ""
dropout: 0.1
learn_sigma: true
class_cond: false
use_checkpoint: false # as in use forward gradient checkpointing
use_scale_shift_norm: true
resblock_updown: true
# use_fp16: false # This we will set with fabric rather than manual
use_new_attention_order: true
norm_type: group

