defaults:
  - _self_
  - model: gd_unet
  - diffusion: cats_gaussian
  - schedule_sampler: uniform

exp:
  seed: 42
  ema_decay: 0.9999

  micro_batch_size: 8
  log_steps: 9
  nfe: 1000

  ckpt_path: outputs/2025-06-01/17-18-30/checkpoints/model_30k.ckpt


fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  precision: 32

wandb:
  entity: jgrzywaczewski
  project: cats_diffusion



