defaults:
  - _self_
  - dataset: cats
  - model: gd_unet
  - diffusion: cats_gaussian
  - schedule_sampler: uniform

dataloader:
  _target_: torch.utils.data.DataLoader
  _partial_: True
  batch_size: 256
  shuffle: False
  num_workers: 1
  pin_memory: True
  persistent_workers: False

exp:
  seed: 42
  ema_decay: 0.9999
  micro_batch_size: 64
  max_iters: 4048 # Random number above 2048

  sampling_method: ddim # ddim, ddpm. dpm, sa
  nfe: 1000


  ckpt_path: outputs/2025-06-01/17-18-30/checkpoints/model_30k.ckpt


fabric:
  _target_: lightning.Fabric
  num_nodes: 1
  devices: 1
  precision: 32

wandb:
  entity: jgrzywaczewski
  project: cats_diffusion



