_target_: guided_diffusion.script_util.create_gaussian_diffusion
steps: 1000
learn_sigma: true
sigma_small: false
noise_schedule: linear
use_kl: false
predict_xstart: false
rescale_timesteps: false
timestep_respacing: ""
rescale_learned_sigmas: false